version: "3.7"
services:
  frontend_app:
    build:
      context: ./frontend/app
      dockerfile: "Dockerfile"
    container_name: ppa-app
    command: ["sh", "-c", "npm run start & nginx -g 'daemon off;'"]
    ports:
      - "80:3000"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/.next
    restart: always
